name: Update pnpm-lock.yaml

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --lockfile-only
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --exit-code || (git commit -am "chore: update pnpm-lock.yaml" && git push)
