# 💸 Help me keep steam clean and my coffee cup full
# These are the methods to fund this madness (aka removing Steam bloat)

github: [] # Maybe one day... when GitHub Sponsors loves me back
patreon: null # I swear I won’t spend it all on CS skins
open_collective: null # Collectively broke, but together
ko_fi: 'l1lkid' # One coffee = 1 less Steam process running ☕
tidelift: null # I don't even know what this does
community_bridge: null # Sounds like a VPN with taxes
liberapay: null # Libre doesn’t mean free, sadly
issuehunt: null # Bug bounty but make it emotional damage
lfx_crowdfunding: null # If you understand this one, you're smarter than me
polar: null # As cold as my donation stats
buy_me_a_coffee: 'l1lkid' # Or two. Or twelve. For better debugging energy
thanks_dev: null # I accept emotional support in banknote form
custom:
