
title: Steam-Debloat
description: Optimize Steam for Low-Resource PCs
baseurl: ""
url: "https://mtytyx.github.io/Steam-Debloat/"
logo: /assets/logo.webp

nav:
  - title: Home
    url: /
  - title: Features
    url: /#-key-features
  - title: Installation
    url: /#-quick-start
  - title: Roadmap
    url: /#-project-roadmap
  - title: Contributing
    url: /#-contributing
  - title: Support
    url: /#-support-and-contact

languages:
  - en
  - es
  - fr
  - pt
  - zh
  - hi

theme: jekyll-theme-cayman

navbar:
  - title: README in English
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.md
  - title: README in Spanish
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.es.md
  - title: README in French
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.fr.md
  - title: README in Portuguese
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.pt.md
  - title: README in Chinese
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.zh.md
  - title: README in हिन्दी
    url: https://github.com/mtytyx/Steam-Debloat/blob/main/README.hi.md

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

